### ISSUE TITLE
404 page demo.html

### ISSUE THREAD

**Issue by ChriStef** [zzarcon/default-passive-events#20]
Please fix the example url at Check the demo.html for a working example.

**Comment by FRSgit** [comment]
@zzarcon can you please set github pages to be run from /docs directory (i don't have priviliges to do so) - [github docs](https://github.com/blog/2228-simpler-github-pages-publishing).

**Comment by FRSgit** [comment]
Ping @zzarcon

**Comment by zzarcon** [comment]
Done! 🍾

**Comment by ChriStef** [comment]
Thank you. One more question, Can I load it with async?

**Comment by FRSgit** [comment]
Thanks @zzarcon! 🎉

@ChriStef - yes and no. You can load package with async but you have to make sure that default-passive-events gets run **before** any call to `addEventListener` method.

That said, IMO the easiest solution would be either to load our package **synchronously** (since its 1,45kB gzipped) **or** to load it **asynchronously** with correct use of  [defer](https://developer.mozilla.org/pl/docs/Web/HTML/Element/script#attr-defer) attribute.

If you think that readme file should be somehow corrected/extended then PRs are welcome, or at least tell us what would you want to add there.

Closing this issue since demo pages are now working well - if you need any additional info please write directly to me.
