### ISSUE TITLE
Issue with Select2 plugin

### ISSUE THREAD

**Issue by lenamtl** [zzarcon/default-passive-events#32]
Hi,

I'm default-passive-events this fixed almost all my issues except one case...

I'm using Select2 plugin for my dropdown and this creating an Error (not a warning) in the browser 
jQuery-2.2.0.min.js:3 Unable to preventDefault inside passive event listener invocation.
and pointing code line related to Select2 mousewheel.

Unable to preventDefault inside passive event listener invocation.

```
if ($.fn.mousewheel) {
      this.$results.on('mousewheel', function (e) {
        var top = self.$results.scrollTop();

        var bottom = self.$results.get(0).scrollHeight - top + e.deltaY;

        var isAtTop = e.deltaY > 0 && top - e.deltaY <= 0;
        var isAtBottom = e.deltaY < 0 && bottom <= self.$results.height();

        if (isAtTop) {
          self.$results.scrollTop(0);

          e.preventDefault();
          e.stopPropagation();
        } else if (isAtBottom) {
          self.$results.scrollTop(
            self.$results.get(0).scrollHeight - self.$results.height()
          );

          e.preventDefault();
          e.stopPropagation();
        }
      });
    }


 if (nullLowestDeltaTimeout) { clearTimeout(nullLowestDeltaTimeout); }
        nullLowestDeltaTimeout = setTimeout(nullLowestDelta, 200);

        return ($.event.dispatch || $.event.handle).apply(this, args);
    }
```

This occured on static list and on my Ajax list.

Anyone have a solution for this?

It's look like similar issue occurred in the past but I don't know how to fix it to make it work with Select2
https://github.com/zzarcon/default-passive-events/issues/19
https://github.com/zzarcon/default-passive-events/issues/5

**Comment by FRSgit** [comment]
Hey @lenamtl! Well, it seems that to use `Select2` jQuery plugin you need to use regular, non-passive events, so they can be prevented by plugin's code. Our library by default makes all event passive and that's why you get an error.
The only solution to this problem I see is to bring back the **original** `addEventListener` method for the element which `Select2` would try to add event listener on. Instructions about how to bring back the original `addEventListener` are written within our [README file](https://github.com/zzarcon/default-passive-events#is-there-a-possibility-to-bring-default-addeventlistener-method-back-for-chosen-elementsglobally-eg-for-time-of-running-some-of-the-code).

So, for example - the basic usage of `Select2` which normally looks like this:
```js
$('.example-select').select2();
```
should be changed in the following way:
```js
const $exampleSelect = $('.example-select');
$exampleSelect[0].addEventListener = $exampleSelect[0].addEventListener._original;
$exampleSelect.select2();
```

Can you check if this solution does fix the problem for you? Waiting for feedback!

**Comment by lenamtl** [comment]
I decided to fix all the warning instead of using your plugin, as it may be hard to catch all errors from each plugin and this will require a lot of tests in my case.

Thanks for the fix I will make a test and let you know as it can help someone else.

**Comment by FRSgit** [comment]
Yea, sure, thanks! The whole point of this library is to use it in the environment when you do have some performance problems (because of libraries not using passive listeners) and you're not sure if libraries creators will add passive events support in the near future.
Ofc it might need extra attention from you, but well, if you have some problematic case - it's the only way to straighten it out.

If there is nothing more I can do here, I'll close the issue. Please respond here when you would be able to test the code I've posted earlier! 💪
