### ISSUE TITLE
About scroll event

### ISSUE THREAD

**Issue by plesiecki** [zzarcon/default-passive-events#34]
Hello 👋 

Interesting utility, I'm keen to give it a spin.

There is something I would like to share about scroll event. I've read some docs recently and I've noticed this: 

> You don't need to worry about the value of passive for the basic scroll event. Since it can't be canceled, event listeners can't block page rendering anyway. 

from [here](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners)

and another note from [here](https://developers.google.com/web/updates/2016/06/passive-event-listeners)
> Note: The basic scroll event cannot be canceled, so it does not need to be set passive.

What are your thoughts on this matter?

**Comment by FRSgit** [comment]
Hey @plesiecki!

I think you might be right - though I cannot find any other sources about that (especially, nothing connected to the [standard itself](https://drafts.csswg.org/cssom-view/#eventdef-document-scroll)). I cannot tell, if this behaviour (not `scroll` event being passive by default) is true in every major browser (chromium-based ones, firefox, safari).

In light of this, I'd **keep the scroll event as a part of this library**.

I'm closing this issue as answered (and also because it's so old I don't expect you to answer 😄). But, if you have other arguments and/or opinion on this topic - I'm happy to reopen and discuss it here!
